### ISSUE TITLE
landmark

### ISSUE THREAD

**Issue by feng98** [zuoqing1988/train-mtcnn#1]
Hi, do you have plan on landmark? I'm very interested in it. @zuoqing1988

**Comment by zuoqing1988** [comment]
加上landmark之后还没有训练出收敛的结果

**Comment by feng98** [comment]
请问能发一份加上landmark后的code吗？我也训练试试，email：987539734@qq.com，谢谢！

**Comment by zuoqing1988** [comment]
不慌

**Comment by zuoqing1988** [comment]
@feng98 @FW2016 可以试试landmark了

**Comment by feng98** [comment]
thanks

**Comment by feng98** [comment]
No such file or directory: '/opt/train-mtcnn/prepare_data/wider_annotations/prob.txt'
P20_gen_data.bat产生anno.txt和train.txt，请问prob.txt是什么呢？ @zuoqing1988

**Comment by zuoqing1988** [comment]
已上传，git pull一下

**Comment by feng98** [comment]
gen_hard_example我运行产生几百万张？ @zuoqing1988

**Comment by Define-ShenYue** [comment]
在跑demo时，执行到Onet的self.executor.forward(is_train=False）这一句时程序会直接退出，pycharm下会报错Process finished with exit code -1073740791 (0xC0000409)，请问是什么原因？ps:不是网上说的显存原因。

**Comment by zuoqing1988** [comment]
不知道你是啥时候跑的，第一，model

**Comment by Define-ShenYue** [comment]
> 不知道你是下载的啥时候的工程跑的？
> 第一，model文件夹里的模型可能与symbol.py里不一致
> 第二，Onet的softmax mode=‘channel’好像会报错，删掉之后可以运行（前提是model文件夹里的模型与symbol.py匹配）
> 你下载最新的，然后按照流程训练，应该能跑起来。

已解决，要删掉“mode = channel”，多谢！

**Comment by gehaocool** [comment]
L_net_onlylandmark的训练epochs需要这么多吗？lr decay在2000和4000epoch，总共5000个epoch，估算了一下要600多个小时……
