### ISSUE TITLE
106landmark的数据集

### ISSUE THREAD

**Issue by guoguoguilai** [zuoqing1988/train-mtcnn#14]
左博士你好，请问您提供的数据集是如何得到的呢？

**Comment by zuoqing1988** [comment]
网上开源的

**Comment by guoguoguilai** [comment]
> 网上开源的

好的，谢谢~

**Comment by Jar7** [comment]
左博您好，请问数据集只用了300w吗？有没有用300vw等其他数据集？

**Comment by zuoqing1988** [comment]
@Jar7 开源数据集都是垃圾，我在ZQCNN下开源的det5-dw112是用私有数据集训练的

**Comment by Jar7** [comment]
> @Jar7 开源数据集都是垃圾，我在ZQCNN下开源的det5-dw112是用私有数据集训练的

感谢回复。我发现det5-dw112检测的点很稳定，在video 下的抖动也比其他开源模型好很多。
能否请教下，
1. 这个模型是用train-mtcnn里的only_landmark106训练出来的吗？
2. 训练集的标注方法是一致的吗？比如所有图片label都是人工标注，或者都是某个机器标注再人工筛之类的吗？想了解下这么稳定的点是不是和训练集有关。

谢谢！

**Comment by zuoqing1988** [comment]
开源的那个模型是我用一线公司SDK标注之后肉眼挑选得一部分。我们自己的商用模型更准，有非常详细的标注规范。

**Comment by Jar7** [comment]
@zuoqing1988 是商用模型在video上的点更稳定吗？比如人脸不动，关键点不会抖动？
能否请教这两个模型训练上有什么区别吗？还是只有训练集的区别？

我现在在用jd数据集，再加上一些其他机器标注的数据集做训练集，在您开源的模型上finetune，结果抖动问题还是很明显。所以我不确定抖动来自于标注规范不统一，还是训练video的时候要加入一些其他约束，比如光流？

请问您只用only_landmark106的方法训练吗？

**Comment by zuoqing1988** [comment]
ZQCNN里有个示例程序SampleVideoFaceDetection里面有逻辑层上的处理，用我们未开源的模型（包括检测模型和关键点模型）可以做到比较稳，但是目前离商汤还有差距。

**Comment by Jar7** [comment]
@zuoqing1988 了解了，非常感谢！
