### ISSUE TITLE
关于loss函数

### ISSUE THREAD

**Issue by guoguoguilai** [zuoqing1988/train-mtcnn#15]
不知道左博有没有考虑过将关键点的loss函数改为wing loss呢，我想这样效果应该会更好一点

**Comment by zuoqing1988** [comment]
你可以试一试，然后写个报告。祖国人民需要你

**Comment by guoguoguilai** [comment]
> 你可以试一试，然后写个报告。祖国人民需要你

哈哈，没接触过MXnet，我尝试实现下

**Comment by guoguoguilai** [comment]
失败了，暂时搁置下
