### ISSUE TITLE
 训练RNet步骤

### ISSUE THREAD

**Issue by lyyiangang** [zuoqing1988/train-mtcnn#18]
hi zuoqing，
Readme里写的RNet训练步骤如下：
```
训练Rnet
(9)双击R_gen_data.bat

生成训练Rnet所需样本
(10)双击R_gen_hard_example.bat

利用训练得到的Pnet20模型，生成用于训练Rnet的hard样本，请用文本方式打开，酌情填写参数
(11)双击R_gen_imglist_with_hard.bat

生成用于训练Rnet的list文件
(12)双击R_train_with_hard.bat

训练Rnet
```
这里只用hand example训练RNet， 会不会导致样本不足， 还需要提前使用crop的24x24图片训练RNet么？

**Comment by zuoqing1988** [comment]
仔细阅读prepare_data\gen_imglist.py

**Comment by lyyiangang** [comment]
prepare_data\gen_imglist.py 里面有针对20和24不同尺寸图片的训练， 同时也包括hard example部分， 单从这里看，应该还需要根据24x24图片生成train_24_24.txt来训练RNet。

**Comment by lyyiangang** [comment]
@zuoqing1988 抱歉打扰了， 我有几行没仔细看， hard example 和R_gen_data.bat 生成的图片都会在gen_imglist.py中使用，他们都会参与RNet的训练。
