### ISSUE TITLE
prob.txt

### ISSUE THREAD

**Issue by wait1988** [zuoqing1988/train-mtcnn#2]
How to generate the prob.txt file?

**Comment by zuoqing1988** [comment]
https://github.com/zuoqing1988/train-mtcnn/blob/master/prepare_data/wider_annotations/prob.txt

**Comment by ckqsars** [comment]
I want to know the meaning of the value in prob.txt. How  can I generate the prob.txt for other dataset.

**Comment by zuoqing1988** [comment]
@ckqsars prob.txt gives the confidence of the groundtruth. Very low confidence means it's hard to say the bbox is positive or negative.

For WIDER faces, I use the original Onet to test each bbox.

I you train some new class for the first time, you can set the confidence be 1.
After training for one round, you can use Pnet\Rnet\Onet to test each bbox.

**Comment by ckqsars** [comment]
Yeah, this is  a useful pretreatment. Thank you for your help.
