### ISSUE TITLE
多个人脸框输出

### ISSUE THREAD

**Issue by lyyiangang** [zuoqing1988/train-mtcnn#21]
hi qing，
在使用人脸检测器检测人脸时， 出现下图多个人脸框， 其中一个错误的人脸框confidence还是很高的。 请问这种问题要怎么重新train模型才能避免呢？
![aflw__face_44436 jpg result](https://user-images.githubusercontent.com/1982228/60853289-f807ce80-a22d-11e9-8185-17cdc1033e81.png)

**Comment by zuoqing1988** [comment]
可能把nms阈值设低点就解决了

**Comment by lyyiangang** [comment]
@zuoqing1988  那如何在train的时候避免这种情况呢？ 比如提高positive sample 的iou阈值

**Comment by zuoqing1988** [comment]
模型设计大一点

**Comment by lyyiangang** [comment]
@zuoqing1988 谢谢指导， 我尝试下。
