### ISSUE TITLE
关键点回归网络训练精度下降问题

### ISSUE THREAD

**Issue by TMaysGGS** [zuoqing1988/train-mtcnn#28]
左博士你好，

非常感谢你开源的MTCNN训练脚本，以及你的ZQCNN框架。

我现在被要求做一个轻量化人脸关键点回归模型的任务，尝试了用你的脚本训练L106_Net和L106_Net_v2两个模型，发现它们往往在训练到100多个epochs的时候关键点很接近真实值，但继续训练下去两个loss在下降，关键点却越来越偏离。我自己也尝试过训练一个关键点回归网络，也遇到类似的问题，即训练之初关键点越来越准确但继续训练下去精度不升反降。

请问是不是训练时有什么需要注意的细节？期待你的回复。

PS：下图前三张分别是L106_Net训练到160、300、470 epoch时的效果查看，后两张是L106_Net_v2训练到100、600 epoch时的效果查看。
![landmarkonly106_160epoch](https://user-images.githubusercontent.com/31966022/64137715-73e85680-ce2c-11e9-9710-3e9cb5802746.jpg)
![landmarkonly106_300epoch](https://user-images.githubusercontent.com/31966022/64137716-7480ed00-ce2c-11e9-87ad-7ca4e494a8f4.jpg)
![landmarkonly106_470epoch](https://user-images.githubusercontent.com/31966022/64137717-75198380-ce2c-11e9-8997-47f5e0849f9c.jpg)
![landmarkonly106_v2_100epoch](https://user-images.githubusercontent.com/31966022/64137719-75198380-ce2c-11e9-8529-e932e3895cdf.jpg)
![landmarkonly106_v2_600epoch](https://user-images.githubusercontent.com/31966022/64137721-75b21a00-ce2c-11e9-8432-80fe48a33243.jpg)

**Comment by zuoqing1988** [comment]
几百个epoch不够，得2000以上

**Comment by TMaysGGS** [comment]
> 几百个epoch不够，得2000以上

好的非常感谢回复，我再去试试。
